### ISSUE TITLE
not enough values to unpack

### ISSUE THREAD

**Issue by asadadams** [ashu10832/Finger-Detection#1]
After pressing a i get an error "not enough values to unpack (expected 3, got 2)"

**Comment by MarkJhonDoe** [comment]
@asadadams @ashu10832 
I'm facing the same issue. How to get it resolved?

**Comment by Acrylo** [comment]
> @asadadams @ashu10832
> I'm facing the same issue. How to get it resolved?

Hello,
Change the code as I've showed in the image. It will be solved..   :)
![Screenshot 2021-03-09 123127](https://user-images.githubusercontent.com/49286031/110431258-8dc6c180-80d3-11eb-9dc5-7999c1071759.jpg)
